complete -c git-ignore -n "__fish_use_subcommand" -s h -l help -d 'Print help information'
complete -c git-ignore -n "__fish_use_subcommand" -s V -l version -d 'Print version information'
complete -c git-ignore -n "__fish_use_subcommand" -s l -l list -d 'List <templates> or all available templates'
complete -c git-ignore -n "__fish_use_subcommand" -s u -l update -d 'Update templates by fetching them from gitignore.io'
complete -c git-ignore -n "__fish_use_subcommand" -s s -l simple -d 'Ignore all user defined aliases and templates'
complete -c git-ignore -n "__fish_use_subcommand" -s a -l auto -d 'Autodetect templates based on the existing files'
complete -c git-ignore -n "__fish_use_subcommand" -f -a "alias" -d 'Manage local aliases'
complete -c git-ignore -n "__fish_use_subcommand" -f -a "template" -d 'Manage local templates'
complete -c git-ignore -n "__fish_use_subcommand" -f -a "init" -d 'Initialize user configuration'
complete -c git-ignore -n "__fish_use_subcommand" -f -a "completion" -d 'Generate shell completion'
complete -c git-ignore -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c git-ignore -n "__fish_seen_subcommand_from alias; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c git-ignore -n "__fish_seen_subcommand_from alias; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List available aliases'
complete -c git-ignore -n "__fish_seen_subcommand_from alias; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from help" -f -a "add" -d 'Add a new alias'
complete -c git-ignore -n "__fish_seen_subcommand_from alias; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from help" -f -a "remove" -d 'Remove an alias'
complete -c git-ignore -n "__fish_seen_subcommand_from alias; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c git-ignore -n "__fish_seen_subcommand_from alias; and __fish_seen_subcommand_from list" -l version -d 'Print version information'
complete -c git-ignore -n "__fish_seen_subcommand_from alias; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help information'
complete -c git-ignore -n "__fish_seen_subcommand_from alias; and __fish_seen_subcommand_from add" -l version -d 'Print version information'
complete -c git-ignore -n "__fish_seen_subcommand_from alias; and __fish_seen_subcommand_from add" -s h -l help -d 'Print help information'
complete -c git-ignore -n "__fish_seen_subcommand_from alias; and __fish_seen_subcommand_from remove" -l version -d 'Print version information'
complete -c git-ignore -n "__fish_seen_subcommand_from alias; and __fish_seen_subcommand_from remove" -s h -l help -d 'Print help information'
complete -c git-ignore -n "__fish_seen_subcommand_from alias; and __fish_seen_subcommand_from help" -l version -d 'Print version information'
complete -c git-ignore -n "__fish_seen_subcommand_from alias; and __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c git-ignore -n "__fish_seen_subcommand_from template; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c git-ignore -n "__fish_seen_subcommand_from template; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List available templates'
complete -c git-ignore -n "__fish_seen_subcommand_from template; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from help" -f -a "add" -d 'Add a new template'
complete -c git-ignore -n "__fish_seen_subcommand_from template; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from help" -f -a "remove" -d 'Remove a template'
complete -c git-ignore -n "__fish_seen_subcommand_from template; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c git-ignore -n "__fish_seen_subcommand_from template; and __fish_seen_subcommand_from list" -l version -d 'Print version information'
complete -c git-ignore -n "__fish_seen_subcommand_from template; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help information'
complete -c git-ignore -n "__fish_seen_subcommand_from template; and __fish_seen_subcommand_from add" -l version -d 'Print version information'
complete -c git-ignore -n "__fish_seen_subcommand_from template; and __fish_seen_subcommand_from add" -s h -l help -d 'Print help information'
complete -c git-ignore -n "__fish_seen_subcommand_from template; and __fish_seen_subcommand_from remove" -l version -d 'Print version information'
complete -c git-ignore -n "__fish_seen_subcommand_from template; and __fish_seen_subcommand_from remove" -s h -l help -d 'Print help information'
complete -c git-ignore -n "__fish_seen_subcommand_from template; and __fish_seen_subcommand_from help" -l version -d 'Print version information'
complete -c git-ignore -n "__fish_seen_subcommand_from template; and __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c git-ignore -n "__fish_seen_subcommand_from init" -l force -d 'Forcefully create config, possibly overwrite existing'
complete -c git-ignore -n "__fish_seen_subcommand_from init" -s h -l help -d 'Print help information'
complete -c git-ignore -n "__fish_seen_subcommand_from completion" -s h -l help -d 'Print help information'
